# export match template
template-define: &default-template
  name: default
  header: | 
    matches.count: ${matches.count}, groups.count: ${groups.count}, groups.keys: ${groups.keys}
    ===========================================================================================

  match : | 
    [${match.start}:${match.end}]${match.value}
  group : | 
    [${group.start}:${group.end}]${group.key}=${group.value}
  
  footer: | 
    ===========================================================================================
    ===="copyright lqwangxg@gmail.com 2023"====================================================

# check content skip or do on condition
# priority descend: skip_ifany, skip_when, do_ifany, do_when
check-patterns-define: &default_check_patterns
  skip_ifany: []
  skip_when: []
  do_ifany: []
  do_when: []

rule-define: &default-rule
  # rule-name
  name: default
  # rule-group
  group: default

  # file name of include/exlude
  #.myapp.yaml is not included.
  include-file: '\w+\.(html|jsp|java|js|css)$'
  #start/end with (log|bak|back|org|\d+) is excluded
  exclude-file: '^(log|bak|back|org|\d+).+(log|bak|back|org|\d+)$'  
  
  # match destination range(spos=startIndex, epos=endIndex + endLength) 
  # if range_start is empty then spos=0
  # if range_end is empty then epos=length(full) or ahead of next range_start
  # optional: if groupname is included in pattern, 
  #  { match.group.name: match.group.nalue } will be saved in ${match_params_map}
  range-start: 
  range-end:

  # regex pattern   
  pattern: 

  export-template:
    <<: *default-template
    name: export  # override the name
  replace-template:
    <<: *default-template
    name: replace # override the name  
    header:       # override the header 
    footer:       # override the footer

  # check full content by regex match
  full-patterns :
    <<: *default_check_patterns
    # write override here

  # check range content by regex match
  range-patterns: 
    <<: *default_check_patterns
    # write override here


  # check match content by regex match
  match-patterns: 
    <<: *default_check_patterns
    # write override here


  # check match content by evaluate
  match-vals: 
    <<: *default_check_patterns
    # write override here

  # process for refreshing params
  # support functions: 
  #  string: len(string), ucase(string), lcase(string)
  #  number: +,-,*,/
  #  compare: <, <=, >, >=, ==
  match-formulas: []

#=========================
# write your custom rules below.
#=========================
rules:
  - <<: *default-rule
    name: "openMultiMessageDialog"
    # regex pattern   
    pattern: (?P<indent>[ ]*)if\((?P<call>openMultiMessageDialog)\((?P<param>[^{]+)\)\s*\)\s*\{(?P<process>[^}]+?)\}
    range_start: \nfunction\s+(?P<function>\w+)\(form\)\s*\{.+?\n\}
    replace-templates:
      match : | 
        ${indent}${call}(${param}, "callbackForRetunWindow");
        ${indent}window["callbackForRetunWindow"] = function (res){
        ${indent}  if(res){${process}}
        ${indent}}